---
global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: "10s"
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    # enable_http2: true
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'picotemp'
    static_configs: 
      - targets: ["localhost:3030"]
  - job_name: svc_discovery
    file_sd_configs:
      - files:
          - "/prometheus/sd_*.json"
          - "/prometheus/sd_*.yml"
          - "/prometheus/sd_*.yaml"
        refresh_interval: "30s"
